# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0003_auto_20160615_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='platform_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='product_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='product_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carsapp.Platform'),
        ),
    ]
