# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0004_auto_20160615_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='trim',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
